
export const Metadata = {
     title: 'Next.js',
     description: 'Generated by Next.js'
}

export default function DashboardLayout({
     children
}: {
     children: React.ReactNode
}) {
     return (
          <html lang="en">
               DashboardLayout
               <body>{children}</body>
          </html>
     )
}